os: linux
language: python

jobs:
    include:
      - python: 3.5
        dist: xenial
      - python: 3.6
        dist: bionic
      - python: 3.7
        dist: bionic
env:
    - REPOSITORY_ORIGIN=plugins
    - YARN_GPG=no 
before_install:
    - sudo apt-get install libudev-dev
    - sudo apt-get install librrd-dev libpython3-dev
install:
    - pip install tox-travis virtualenv

script:
    - sh .travis.sh
